# Site
repository: feigaoxyz/feigaoxyz.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Fei Gao (高斐)
title: Group Manager / Senior Scientist
email: gaofei<at>ihpc.a-star.edu.sg (work) OR contact<at>feigao.org (personal)
# website: feigao.org

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: feigaoxyz
orcid_username: 0000-0002-1623-4296
github_username:  feigaoxyz
# googlescholar_username: lszau20AAAAJ

# twitter_username: facespics
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
gtag: "G-CWKMMN26Q8"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Group Manager and Senior Scientist at [Computing & Intelligence Department](https://www.a-star.edu.sg/ihpc/ihpc-research-capabilities/computing-intelligence) of [Institute of High Performance Computing (IHPC)](https://www.a-star.edu.sg/ihpc), [Agency for Science, Technology and Research (A*STAR)](https://www.a-star.edu.sg/), Singapore. My R&D aim is to solve real-world challenges with Machine Learning and Optimisation techniques.

  My group is actively seeking outstanding Research Scientists and Interns to join us and work together in Text Understanding and Generation for MedTech and FinTech. <mark>Please drop me your CV today!!</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institute of High Performance Computing (IHPC), A*STAR
        link: https://www.a-star.edu.sg/ihpc
        # link_text: boringcompany.com
        sub_title: October 2013 - Present
        # caption: 
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - April 2021 - Present: Group Manager / Senior Scientist
            - April 2020 - March 2021: Group Manager / Scientist
            - October 2013 - March 2020: Scientist

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Zhejiang University, China
        sub_title: Doctor of Natural Science, Applied Mathematics
        caption: 2013
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Thesis: Combinatorial approaches to several selected topics in coding theory

          Supervisor: [Prof. Gennian Ge](http://staff.ustc.edu.cn/~drzhangx/group-chn/default.html)

      - layout: left
        title: Zhejiang University, China
        sub_title: Bachelor's Degree in Science
        caption: 2008
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Thesis: Constant Composition Codes with Weight Three

          Thesis Supervisor: [Prof. Gennian Ge](http://staff.ustc.edu.cn/~drzhangx/group-chn/default.html)


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
